### ISSUE TITLE
This bot returning true when glitch happens in website like"This field is required"

### ISSUE THREAD

**Issue by Ravgautam** [dmitry-kostin/termin-buchen#12] opened 2023-10-31 08:52 UTC
[runner]: started iteration 1
[findSlot]: error TimeoutError: Waiting for element to be located By(xpath, //*[@id="messagesBox"]/ul/li)
Wait timed out after 60137ms
[runner]: iteration 1 result: true

**Comment by wrapper** [comment] 2023-11-08 09:28
Also getting this issue now:

 The script gets stuck on this screen after a few tries, fails and then sends notification saying it found an appointment: 

![image](https://github.com/dmitry-kostin/termin-buchen/assets/1025364/f54456dd-766f-4688-9b1d-fffaa3afe881)

Console says:

`[runner]: started iteration 4
[findSlot]: error TimeoutError: Waiting for element to be located By(xpath, //*[@id="messagesBox"]/ul/li)
Wait timed out after 60070ms
[runner]: iteration 4 result: true
`

**Comment by dmitry-kostin** [comment] 2023-11-08 21:29
Well, ya now I can confirm that this glitch can happen occasionally. I will try to take a look as soon as I have some spare time. Meanwhile your best bet is just to check and restart if that happens

**Comment by AshishRKO** [comment] 2023-11-13 06:34
Not occasionally. It is happening every time because the Read "messagesBox" is not showing when there are no appointments available

**Comment by tjomagavk** [comment] 2024-01-24 07:47
@dmitry-kostin I fixed it and opened [PR](https://github.com/dmitry-kostin/termin-buchen/pull/19)

**Comment by dmitry-kostin** [comment] 2024-01-24 14:44
thanks, this is merged now!

**Closed as completed by dmitry-kostin** 2024-01-24 14:44 UTC
